version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tests
      POSTGRES_USER: local
      POSTGRES_PASSWORD: docker
